In [12]:

#A Simple Option: Drop Columns with Missing Values


import pandas as pd
from sklearn.model_selection import train_test_split





X = pd.read_csv("MELBOURNE_HOUSE_PRICES_LESS.csv")
#print(X.head())

#read.head()
# Get names of columns with missing values
cols_with_missing = [col for col in X_train.columns
                     if X_train[col].isnull().any()]
print(cols_with_missing)
# Drop columns in training and validation data
reduced_X = X.drop(cols_with_missing, axis=1)


print("MAE from Approach 1 (Drop columns with missing values):")
reduced_X.head()
#print(score_dataset(reduced_X_train, reduced_X_valid, y_train, y_valid))

['Price']
MAE from Approach 1 (Drop columns with missing values):

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council

In [25]:
import numpy as np
from sklearn.impute import SimpleImputer